null_resource.upload_user_flow (local-exec): <Error><Message>An error has occurred.</Message><ExceptionMessage>No MediaTypeFormatter is available to read an object of type 'HttpError' from content with media type 'application/problem+json'.</ExceptionMessage><ExceptionType>System.Net.Http.UnsupportedMediaTypeException</ExceptionType><StackTrace>   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
null_resource.upload_user_flow (local-exec):    at Microsoft.Cpim.Web.Admin.ExceptionManager.RemoveStackTracesIfNeeded(HttpResponseMessage response) in C:\__w\1\s\src\Production\Web.Admin\ExceptionManager.cs:line 645
null_resource.upload_user_flow (local-exec):    at Microsoft.Cpim.Web.Admin.CpimRequestMessageHandler.&lt;SendAsync&gt;d__0.MoveNext() in C:\__w\1\s\src\Production\Web.Admin\CpimRequestMessageHandler.cs:line 40
null_resource.upload_user_flow (local-exec): --- End of stack trace from previous location where exception was thrown ---
null_resource.upload_user_flow (local-exec):    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
null_resource.upload_user_flow (local-exec):    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
null_resource.upload_user_flow (local-exec):    at System.Web.Http.HttpServer.&lt;SendAsync&gt;d__24.MoveNext()</StackTrace></Error>
null_resource.upload_user_flow: Creation complete after 1s [id=7675197542013355465]



data "http" "access_token" {
  url = "https://login.microsoftonline.com/${azurerm_aadb2c_directory.tenant.tenant_id}/oauth2/v2.0/token"
  
  request_headers = {
    "Content-Type" = "application/x-www-form-urlencoded"
  }
  
  request_body = "grant_type=client_credentials&client_id=${module.tenant.client_id}&client_secret=${module.tenant.client_secret}&scope=https://graph.microsoft.com/.default"
}

locals {
  access_token = jsondecode(data.http.access_token.response_body)["access_token"]
}

resource "null_resource" "upload_user_flow" {
  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = <<-EOT
      curl -X PUT \
           -H "Content-Type: application/json" \
           -H "Authorization: Bearer ${local.access_token}" \
           --data-binary "@userflow.json" \
           "https://main.b2cadmin.ext.azure.com/api/adminuserjourneys?tenantId=${var.rg_name}.onmicrosoft.com"
    EOT
  }
}



function Add-UserFlow {
  param(
    [string] $B2CTenantName,
    [string] $DefinitionFilePath
  )

  $B2CTenantId = "$($B2CTenantName).onmicrosoft.com"

  # Get access token for the B2C tenant with audience "management.core.windows.net".
  $managementAccessToken = $(az account get-access-token --tenant $B2CTenantId --query accessToken -o tsv)

  Write-Host "Creating $($DefinitionFilePath) user flow..."
  $signinFlowContent = Get-Content $DefinitionFilePath
  # Using WebRequest here, because Microsoft Graph is currently not able to create user flows with custom properties.
  Invoke-WebRequest -Uri "https://main.b2cadmin.ext.azure.com/api/adminuserjourneys?tenantId=$($B2CTenantId)" `
    -Method "POST" `
    -Headers @{
      "Authorization" = "Bearer $($managementAccessToken)";
      "Content-Type" = "application/json"
    } `
    -Body $signinFlowContent
}


│ Error: Invalid index
│ 
│   on main.tf line 85, in locals:
│   85:   access_token = jsondecode(data.http.access_token.response_body)["access_token"]
│     ├────────────────
│     │ data.http.access_token.response_body is "{\"error\":\"invalid_resource\",\"error_description\":\"AADSTS500011: The resource principal named https://main.b2cadmin.ext.azure.com was not found in the tenant named azb2cpocemeka. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 0d57c3ee-b077-4309-b733-5b74744f0800 Correlation ID: 46ce202e-27d6-4a69-b26d-a0f5eaddca86 Timestamp: 2024-03-04 23:14:41Z\",\"error_codes\":[500011],\"timestamp\":\"2024-03-04 23:14:41Z\",\"trace_id\":\"0d57c3ee-b077-4309-b733-5b74744f0800\",\"correlation_id\":\"46ce202e-27d6-4a69-b26d-a0f5eaddca86\",\"error_uri\":\"https://login.microsoftonline.com/error?code=500011\"}"
│ 
│ The given key does not identify an element in this collection value.




resource "null_resource" "add_user_flow" {
  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = <<-EOT
      # Get access token for the B2C tenant
      access_token=$(az account get-access-token --tenant ${var.b2c_tenant_name}.onmicrosoft.com --query accessToken -o tsv)

      # Creating user flow
      curl -X POST \
           -H "Authorization: Bearer $access_token" \
           -H "Content-Type: application/json" \
           --data-binary "@${path.module}/${var.definition_file_path}" \
           "https://main.b2cadmin.ext.azure.com/api/adminuserjourneys?tenantId=${var.b2c_tenant_name}.onmicrosoft.com"
    EOT
  }
}



<Error><Message>An error has occurred.</Message><ExceptionMessage>The following ClaimType id(s) are not valid self asserted asserted claims: extension_OrgLegacyID</ExceptionMessage><CorrelationId>48c4d9f4-555b-4e73-bc08-728fb86ae41c</CorrelationId><Code>AADB2C</Code><StackTrace /></Error>
null_resource.add_user_flow: Creation complete after 3s [id=81311815175192714]




Error: Creating user flow attribute "Business Service Authorisation"
│ 
│   with module.attributes.azuread_user_flow_attribute.bsa,
│   on attributes/user attributes.tf line 7, in resource "azuread_user_flow_attribute" "bsa":
│    7: resource "azuread_user_flow_attribute" "bsa" {
│ 
│ UserFlowAttributesClient.BaseClient.Post(): unexpected status 404 with OData error: AADB2C90063: There is a problem with the service.




https://main.b2cadmin.ext.azure.com/api/adminuserjourneys/B2C_1_signin?tenantId=azb2cpocemeka.onmicrosoft.com
